### ISSUE TITLE
Re-tag 1.018 as 1.0.18?

### ISSUE THREAD

**Issue by hartwork** [svn-all-fast-export/svn2git#105]
@tnyblom it looks like something went wrong during [release tagging today](https://github.com/svn-all-fast-export/svn2git/releases). The previous format was 1.0.xy and now we have 1.0xy, missing a dot. Any objections to re-tagging as 1.0.18?

Thanks and best, Sebastian

**Comment by tnyblom** [comment]
Oups, sorry about that. Hope it's fixed now.

**Comment by hartwork** [comment]
Thank you!
