### ISSUE TITLE
1 Svn Repository to 60 Git Repositories - Out of memory, malloc failed

### ISSUE THREAD

**Issue by supernaughty** [svn-all-fast-export/svn2git#108]
Hello. I'm trying to use svn-all-fast-export to migrate our SVN project.

Out team used SVN Repository very not useful

they made a main repository, and put sub repositories to that main repository
so main repository is over 30000 revisions, and have lots of file size ...

Main Repository
     |- Sub Repository 1
          | |-branches
          | |- tags
          | |- trunk
     |- Sub Repository 2
          | |-branches
          | |-tags
          | |-trunk
  .... 

By the way, I need to separate these sub repository to each git repositories.
(Sub)Repository 1
|-branches
|-tags
|-trunk
(Sub)Repository 2
|-branches
|-tags
|-trunk
...

I typed these things to Rule file, and svn2git program worked.
but, when passing 3000 revisions, Out of memory error happened.

I thought it using too much git repositories, I tried to convert just one repository to rule files,
but it rejected because of rule is not correct.
because, program may read other sub repository, because i didn't typed to rule file about it.

Error message is 

fatal : Out of memory, malloc failed (tried to allocate 1468122 bytes)
warning: die() called many times. Recursion error or racy threaded death!
fatal: internal consistency error creating the index

is there any good way to solve this problem..? T_T

**Comment by eeijlar** [comment]
See my comments here, might help:
https://github.com/svn-all-fast-export/svn2git/issues/70

**Comment by supernaughty** [comment]
> See my comments here, might help:
> #70

Thanks for your Reply!
It is helpful to me. I should modify my rule file.
and I expanded my memory size twice and out of memory is disappeared.
