### ISSUE TITLE
Option to define a output subdirectory

### ISSUE THREAD

**Issue by jmvermeulen** [svn-all-fast-export/svn2git#24]
I've successfully converted a large SVN repo.
Only use-case issue I'm facing is that all the matching SVN folders come together in the Git root folder.

SVN
```
--Product1/branches/1.0
----file1.txt
--Product2/branches/1.0
----file2.txt
```

Output to:

```
--/
--file1.txt
--file2.txt
```

I would like to specify a subfolder within the output repo, like:
```
match /([^/]+)/branches/([^/]+)/
  repository git-repo
  branch \2
  directory \1 -- statement example 
end match
```

Outputting as:
```
--Product1/file1.txt
--Product2/file2.txt
```

**Comment by temporafugiunt** [comment]
You already have that ability with the prefix attribute, I had the same issue and used the prefix attribute to make proper subdirectories as I pulled things over.

I used it to pull things without regular expressions, like this:
match /trunk/subdirectory1/
  repository NewGitRepo
  branch develop
  prefix subdirectory1/
end match

And I also used it to pull with regular expressions, like this:
match /trunk/([^/])+Service/
  repository NewGitRepo
  branch develop
  prefix \1Solution
end match
