### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by bforesman** [svn-all-fast-export/svn2git#29]
On Ubuntu 16.04 LTS:

Error:
`$ qmake && make`

> cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/me/src/svn2git/src/src.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/me/src/svn2git/src'
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVER="\"5caa913b3ac6fea8ea3a92558889a12e7feed21e\"" -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I. -I/usr/include/subversion-1 -I/usr/local/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/apr-1 -I/usr/local/include/apr-1 -I. -o ruleparser.o ruleparser.cpp
ruleparser.cpp:18:23: fatal error: QTextStream: No such file or directory
compilation terminated.
Makefile:211: recipe for target 'ruleparser.o' failed
make[1]: *** [ruleparser.o] Error 1
make[1]: Leaving directory '/home/me/src/svn2git/src'
Makefile:42: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

Dependencies are installed:
...with the exception that *qt-qmake* needed to be *qt5-qmake* (Documentation issue):

`$ sudo apt-get install qt-qmake' #this doesn't work

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt-qmake

`$ apt-cache policy build-essential subversion git qtchooser qt5-qmake qt5-default libapr1 libapr1-dev libsvn-dev`
 
> build-essential:
  Installed: 12.1ubuntu2
  Candidate: 12.1ubuntu2
  Version table:
 *** 12.1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
subversion:
  Installed: 1.9.3-2ubuntu1
  Candidate: 1.9.3-2ubuntu1
  Version table:
 *** 1.9.3-2ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
git:
  Installed: 1:2.7.4-0ubuntu1
  Candidate: 1:2.7.4-0ubuntu1
  Version table:
 *** 1:2.7.4-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
qtchooser:
  Installed: 52-gae5eeef-2build1~gcc5.2
  Candidate: 52-gae5eeef-2build1~gcc5.2
  Version table:
 *** 52-gae5eeef-2build1~gcc5.2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
qt5-qmake:
  Installed: 5.5.1+dfsg-16ubuntu7.2
  Candidate: 5.5.1+dfsg-16ubuntu7.2
  Version table:
 *** 5.5.1+dfsg-16ubuntu7.2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     5.5.1+dfsg-16ubuntu7 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
qt5-default:
  Installed: 5.5.1+dfsg-16ubuntu7.2
  Candidate: 5.5.1+dfsg-16ubuntu7.2
  Version table:
 *** 5.5.1+dfsg-16ubuntu7.2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     5.5.1+dfsg-16ubuntu7 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
libapr1:
  Installed: 1.5.2-3
  Candidate: 1.5.2-3
  Version table:
 *** 1.5.2-3 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
libapr1-dev:
  Installed: 1.5.2-3
  Candidate: 1.5.2-3
  Version table:
 *** 1.5.2-3 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
libsvn-dev:
  Installed: 1.9.3-2ubuntu1
  Candidate: 1.9.3-2ubuntu1
  Version table:
 *** 1.9.3-2ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

I do see:
`$ ll /usr/lib/x86_64-linux-gnu/qt5/bin/qmake`
> -rwxr-xr-x 1 root root 3071144 Sep 19  2016 /usr/lib/x86_64-linux-gnu/qt5/bin/qmake*

Can you assist?

**Comment by Vampire** [comment]
Maybe the `5` actually is wrong? I'm building with QT4 and have no problems.

**Comment by hartwork** [comment]
In the log above I find:
1. An import error for `QTextStream` (that I found part of both Qt 4.2 and 5.x)
2. Qt4 include paths passed to the compiler
3. Qt5 QMake and `qt5-default`

My guess is that (2) and (3) together do not work.

Lastest `master` builds fine with Qt5 on Ubuntu 18.04 and this report is from 2017 so I'll close the ticket as obsolete but please feel free to re-open as needed!
