### ISSUE TITLE
Assertion `svn_dirent_is_canonical(base, pool)' failed

### ISSUE THREAD

**Issue by alexouzounis** [svn-all-fast-export/svn2git#3]
Hi,

I am running the command below but it appears that there is an assertion failure. I tried with and without a leading / on the URI without any luck.

`svn-all-fast-export --identity-map=authors.txt --rules=standard-rules-development.txt --stats --add-metadata https://svn.com/svn/MyRepo
Invoked as:' svn-all-fast-export --identity-map=authors.txt --rules=standard-rules-development.txt --stats --add-metadata https://svn.com/svn/MyRepo'
Loading rules from: "standard-rules-development.txt" 
Loading rules from "standard-rules-development.txt" 
Creating new repository "MyRepo" 
svn-all-fast-export: subversion/libsvn_subr/dirent_uri.c:972: svn_dirent_join: Assertion 'svn_dirent_is_canonical(base, pool)' failed.
Aborted (core dumped)`

**Comment by tnyblom** [comment]
Hi,

It looks like you are trying to use an svn repository that is not local. You need to have the svn repo from the server available as files for this program to work. Ie accessing a remote repo as svn:// or http(s):// does not work.

/Cheers

**Comment by alexouzounis** [comment]
indeed, my misunderstanding. Did an svndump and run the tool. Cant say how pleased I was to see this tool go so fast compared to others i tried. Converted 70,000+ revisions in an hour approximately.

**Comment by freephile** [comment]
I get this error with the file:///path/to/repo (ra_local) protocol

**Comment by marcelolfilho** [comment]
I'm facing the same problem, so will not work if I use `svn://` or `http(s)://`? I tried the both ways already and still getting this error.

**Comment by tnyblom** [comment]
Unless my memory fails me you need a dump of the server side repo mounted in a path that is accessible as a plain file path.
