### ISSUE TITLE
Warning for every new branch

### ISSUE THREAD

**Issue by moritz-h** [svn-all-fast-export/svn2git#30]
I get this warning:
`Exporting revision 1 .WARN: Branch "master" in repository "test1" doesn't exist at revision 1 -- did you resume from the wrong revision?`

It seems this warning only appears when a new branch is created (for rev 1 there was no git created branch before). So I'm not sure if should care about this warning.

If this happens normally for every new branch I would feature request to not show this warning.

**Comment by Vampire** [comment]
No it does not. It just means that at that revision an out-of-the-blue commit was found to a previously not existing branch. Usually branches should be branched off something. But there is no copy-action, but just add-files as first commit on that branch, you might have started from the wrong revision and the branch was created earlier with files you would miss now.

If those branches really were created out of nothing in the mentioned revision, the warning is acceptable. Especially for the first commit on `trunk` / `master`, this is of course ignorable in most cases if you started to import from the first revision.

**Comment by tnyblom** [comment]
Merged
