### ISSUE TITLE
svn:global-ignores not considered when generating .gitignore files and patterns are not transformed properly

### ISSUE THREAD

**Issue by Vampire** [svn-all-fast-export/svn2git#34]
@alexgit2k implemented the ability to generate `.gitignore` entries from `svn:ignore` properties.
"Unfortunately" since SVN 1.8 there is also `svn:global-ignores` which basically is the same, but works on all subdirectories, not only on the directory where it is specified, like `/*.java` vs. `*.java` in `.gitignore`.

It would be great if svn2git would also support the `svn:global-ignores` which it currently only warns about if you ask it to. @alexgit2k could you maybe give it a shot? :-)

**Comment by Vampire** [comment]
Actually it is even worse I think.
As far as I can see from a quick look, you just copy over `svn:ignore` to `.gitignore`.
This is not valid, e. g. they are working like if it would be `svn:global-ignores`, on all subdirectories.
For `svn:ignore` each entry needs to be be prefixed with `/` to only matchin the directory where the `.gitignore` resides and the patterns also have to be slightly modified, as Subversion e. g. supports character classes with `[...]`.

**Comment by Vampire** [comment]
The function used for matching the patterns is https://apr.apache.org/docs/apr/2.0/group__apr__fnmatch.html#gabe9c7d7efe6afc203a01befbc45bad96 without flags

**Comment by Vampire** [comment]
Ah, Git treats the patterns similar. I think just only-here vs. everywhere underneath and special treatment for multiple consecutive asterisks is neccessary which are the same as one asterisk in SVN but mean any level of subdirectories in Git if there are two or are invalid if there are more than two.

So I guess what needs to be done is

- Replacing any sequence of asterisks by one asterisk
- for `svn:ignore` prefix each line with a slash
- for `svn:global-ignores` also generate `.gitignore` or add to existing, but without slash in the beginning
- for `svn:global-ignores` split the pattern on `\n`, `\r`, `\t`, `\v` and ` ` as that is what Subversion supports for `svn:global-ignores` opposed to `.gitignore` which only `svn:ignore` which only supports linebreaks

**Comment by Vampire** [comment]
Btw. is the `.gitignore` removed if the `svn:ignore` (and `svn:global-ignores`) is removed?

**Comment by Vampire** [comment]
Ok, as I already found out everything, I also fixed it. :-D

**Comment by tnyblom** [comment]
Thanks!
