### ISSUE TITLE
Is it possible to handly moving subpathes

### ISSUE THREAD

**Issue by opensource21** [svn-all-fast-export/svn2git#38]
I'm evaluating how to migrate our svn-repositories to git. At the moment we have multi project repositories. So we need to export subpathes to different git repositories. The problem is that the structure was changed over the time. 

At the moment I try the following approach: 

1.  `run log -xml -v <mySubPath>`
2. find in which revisionRange <mySubPath> has a specific path 
3. make an specific migration for this range.

Let explain it on a simple example with the following history

 * r1 Directory a1 was created
 * r5 Director a1 was renamed to a5
 * r10 Directory a5 was rename to b

I'm unsure if this is possible with svn-all-fast-export.  Can someone give me a hint?

**Comment by oskarb** [comment]
Write a match rule for each directory name. Specify the same target repository and branch and the tool seems to do the right thing. Or use regexp to match them all with one rule for the same effect.

**Comment by opensource21** [comment]
At the end of the day I find out, that it's possible. Unfortunately I had to write really complex rules. Another problem is that if path /a/b/c is non relevant at revision 47 but still exists there the path will stay there and won't be removed-
