### ISSUE TITLE
Commits not visible after a "stuck" revision

### ISSUE THREAD

**Issue by ymartin59** [svn-all-fast-export/svn2git#39]
I run `svn-all-fast-export --rules standardlayout.rules  --identity-map mapping.txt --svn-ignore --add-metadata --stats svn-repository`
And it is processed up to latest revision 19018 according logs, and git bare repository size sounds correct.
But "master" reference is stuck to revision 10090, `git log master` last commit shown is `svn path=/trunk/; revision=10090`. Branches and tags created after that revision are not visible either. 

If I run `svn-all-fast-export` again, it starts back to revision 10091... Investigating git bare repository, I find out as many `objects/pack/tmp_pack_XXXX` large files.

Do I guess right commits have not been "flushed" into repository ? What should I do to complete migration and get "recent" references visible ?

Thank you in advance for your help

**Comment by Ditti4** [comment]
I've encountered the same issue. All revisions up to 31416 were imported correctly, everything after that was not, with the one existing `tmp_pack` file being 88 GB in size (yep, that repository is *huge*).

So I started digging around in the code. My first assumption was that `git fast-import` wasn't called in some odd edge-case. I tried calling it in `main.ccp`, which didn't help.

Digging further into the code, I found under what circumstances `git fast-import` would be started in the normal workflow and tried playing with the `--commit-interval` command line option. Its default is a conservative interval of 10k commits but that obviously didn't work in my case, so I lowered it to 500. Everything seemed to work fine, newer commits started to be imported.

However, I still wasn't happy with this and I dug around some more. This is when I found that at the very end of the `main` function in `main.cpp` the `finalizeTags()` function is called and right afterwards the `repo` pointer is freed:

```cpp
foreach (Repository *repo, repositories) {
    repo->finalizeTags();
    delete repo;
}
```

The `finalizeTags()` function will call `startFastImport()`, which calls `git fast-import` in the background. In the destructor of `FastImportRepository`, the function [`closeFastImport()`](https://github.com/svn-all-fast-export/svn2git/blob/master/src/repository.cpp#L468) is called. It will wait for the process to finish for the default amount of time, which is 30 seconds, and will then terminate the process.

Those 30 seconds are way too short of a period to successfully import a 88 GB pack file. What I did to work around that was to implement a `--fast-import-timeout` option which accepts a number of seconds to use as the custom timeout. If an argument of 0 is given, it will just wait forever.

This seemed to work very well for an 18 GB pack file, but I'm running another full test with the complete history to verify that my approach works before I submit a pull request.

What you could try to manually flush that pack file to the repository is calling the `git fast-import` command manually like it is done [here](https://github.com/svn-all-fast-export/svn2git/blob/master/src/repository.cpp#L777). However, I didn't try that manual approach.
