### ISSUE TITLE
Exporting revision 1 "/content/" did not match any rules; cannot continue

### ISSUE THREAD

**Issue by marcusds** [svn-all-fast-export/svn2git#41]
I am getting the error: Exporting revision 1 "/content/" did not match any rules; cannot continue

/content/ is a directory in trunk and each branch, but why would it be part of the match? I'm really confused.

My SVN rules are:
```
#
# Declare the repositories we know about:
#

create repository pw_content
end repository

#
# Declare the rules
# Note: rules must end in a slash
#

match /trunk/
  repository pw_content
  branch master
end match

match (branch|tag)/([^/]+)/
 repository pw_content
  branch \2
end match
```

**Comment by marcusds** [comment]
Pro-tip, just because your repo has /trunk/ etc in the recent commits, doesn't mean 50,000 commits ago it used that structure.

**Comment by Vampire** [comment]
Pro-tip, use https://blog.hartwork.org/?p=763 as base to build your rules. ;-)
