### ISSUE TITLE
Remaining old files if SVN copy operations replace directories

### ISSUE THREAD

**Issue by gebae** [svn-all-fast-export/svn2git#43]
I had to migrate a large SVN repo but run into trouble.
After analyzing the problem a bit, it seems that SVN copy operations for directories which replace 
older directories are problematic, because svn2git does not delete all the old content in this case
(as SVN does it).

Are there any options to work around (or resolve) the problem? Will it be possible to fix this in the tool?

To illustrate the problem, I created a very small test repository showing the problem. The output of "svn log -v" can be found in attached file svn_log.txt.

Basically a file in trunk is created (folder_a/file1.txt), then a branch is created (branch1) from trunk,
the first file is deleted and another file is created (folder_a/file2.txt) and another branch from trunk is created (branch2). 
Finally the directory folder_1 from branch2 is copied to branch1 replacing the older directory folder_a.
In SVN the older file folder_a/file1.txt is then (implicitly) deleted. But after migrating to Git it is 
still there :-(

[svn_log.txt](https://github.com/svn-all-fast-export/svn2git/files/1852420/svn_log.txt)

**Comment by gebae** [comment]
####
Steps to easily 

reproduce the problem
####
# 0.) Make sure to have the following files
#   * svn-test9.dmp
#   * rules.conf
#   * authors.txt

# 1.) Prepare SVN repository
svnadmin create svn-test9-repo && \
cat svn-test9.dmp | svnadmin load svn-test9-repo

# 2.) Do the migration
/opt/migration/bin/svn-all-fast-export \
    --identity-map ./authors.txt \
    --rules ./rules.conf \
    --add-metadata-notes --empty-dirs --svn-ignore --propcheck --svn-branches \
    $(readlink -f ./svn-test9-repo)
# Note the warning: "WARN: repository git-test9-repo branch branch1 has some files copied from branch2@5"    
    
# 3.) Check the results
git clone -b branch1 git-test9-repo git-test9-checkout
ls -l git-test9-checkout/folder_a/
# You will see now both test files, file1.txt and file2.txt, in Git.
# But the SVN checkout is different - branch1 will not contain file1.txt:
svn co file://$(readlink -f ./svn-test9-repo)/branches/branch1 ./svn-test9-checkout
ls -l svn-test9-checkout/folder_a/ 

[files_to_reproduce.zip](https://github.com/svn-all-fast-export/svn2git/files/1852423/files_to_reproduce.zip)

**Comment by gebae** [comment]
oops, I don't wanted to close... :)

**Comment by kfsone** [comment]
Running into the same issue. I collapsed the svn dump file down to this:

```
Revision-number: 1  Imported folder structure

add dir branches
add dir tags
add dir trunk
------------------------------------------------------------------------------
Revision-number: 2  add folder folder_a and file folder_a/file1.txt

add dir trunk/folder_a
add file trunk/folder_a/file1.txt
------------------------------------------------------------------------------
Revision-number: 3  create branch branch1

add dir branches/branch1 from trunk:2
------------------------------------------------------------------------------
Revision-number: 4  delete file folder_a/file1.txt + add file  folder_a/file2.txt

add file trunk/folder_a/file2.txt
del file trunk/folder_a/file1.txt
------------------------------------------------------------------------------
Revision-number: 5  create branch branch2

add dir branches/branch2 from trunk:4
------------------------------------------------------------------------------
Revision-number: 6  replace folder_a of branch1 with folder_a of branch2

del branches/branch1/folder_a
add branches/branch1/folder_a from branches/branch2/folder_a:5
```

The issue here is that very last entry, and here's the original:

```
Node-path: branches/branch1/folder_a
Node-action: delete

Node-path: branches/branch1/folder_a
Node-kind: dir
Node-action: add
Node-copyfrom-rev: 5
Node-copyfrom-path: branches/branch2/folder_a
```

The folder-delete isn't being honored first. So this is definitely a bug.

I'm running into the same thing :(

**Comment by kfsone** [comment]
Further digging: svn_fs_path_change_replace is actually what's being seen by svn.cpp:622.

**Comment by Vampire** [comment]
I hit the same problem today, it can be reproduced even easier with two commits, but only when `--empty-dirs` is used:

```bash
svnadmin create repo
svn co file:///.../repo/ ws
cd ws
mkdir foo bar
echo foo-a >foo/a
echo foo-b >foo/b
echo bar-a >bar/a
svn add *
svn ci -m setup
svn rm foo
svn mv bar foo
svn ci -m replace
```
and the rules file
```
create repository git-repo
end repository

match /
    repository git-repo
    branch master
end match
```
and then the command
```bash
svn2git --rules svn2git.rules repo --empty-dirs && git -C git-repo ls-tree @ -r
```
