### ISSUE TITLE
"create repository" ... doesn't

### ISSUE THREAD

**Issue by kfsone** [svn-all-fast-export/svn2git#54]
[When using dry-run]

As trivial as they come: first run, you sort of expect it to git init the directory for you if its absent, partly because of the amount of text to declare one:

```
create repository foo
end repository
```

but the absence of the repos still causes progress to halt, preventing you from doing a dry-run...

The use of the term "name" also sets up a false hope that the above would create a "foo.git" folder for me and use that.

**Comment by Vampire** [comment]
I'm not sure what you mean.
Yes, a dry-run will not create the repositories, because it is a dry-run.
But the dry-run does not need the repositories to be there either, because it is a dry-run.

**Comment by Vampire** [comment]
Do you have an MVCE where this happens?
As I said, here it works perfectly fine with dry-run and without the repositories being present.
