### ISSUE TITLE
Build on OSX?

### ISSUE THREAD

**Issue by grandemtn** [svn-all-fast-export/svn2git#61]
Any help getting this to build on osx?

Thanks to brew, I think I have almost everything installed, but I'm getting the error below.  I think I'm missing some svn libs, but I'm not certain how to get them.  Hoping someone else has done this before and can help.

Thanks!

qmake && make
Info: creating stash file /Users/macfly/dmjohns/svn-all-fast-export/.qmake.stash
cd src/ && ( test -e Makefile || /usr/local/opt/qt/bin/qmake -o Makefile /Users/macfly/dmjohns/svn-all-fast-export/src/src.pro ) && /Library/Developer/CommandLineTools/usr/bin/make -f Makefile
Project WARNING: Qt has only been tested with version 10.13 of the platform SDK, you're using 10.14.
Project WARNING: This is an unsupported configuration. You may experience build issues, and by using
Project WARNING: the 10.14 SDK you are opting in to new features that Qt has not been prepared for.
Project WARNING: E.g., 10.14 enables dark mode and layer-backed views, which Qt 5.11 does not support.
Project WARNING: Please downgrade the SDK you use to build your app to version 10.13, or configure
Project WARNING: with CONFIG+=sdk_no_version_check when running qmake to silence this warning.
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DVER="\"83d6f8d2b28e7db5c1ac959df96fc74af363ab92\"" -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I. -I/usr/include/subversion-1 -I/usr/local/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/apr-1 -I/usr/local/include/apr-1 -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I. -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib -o ruleparser.o ruleparser.cpp
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DVER="\"83d6f8d2b28e7db5c1ac959df96fc74af363ab92\"" -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I. -I/usr/include/subversion-1 -I/usr/local/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/apr-1 -I/usr/local/include/apr-1 -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I. -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib -o repository.o repository.cpp
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DVER="\"83d6f8d2b28e7db5c1ac959df96fc74af363ab92\"" -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I. -I/usr/include/subversion-1 -I/usr/local/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/apr-1 -I/usr/local/include/apr-1 -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I. -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib -o svn.o svn.cpp
svn.cpp:528:13: warning: 'svn_fs_paths_changed2' is deprecated [-Wdeprecated-declarations]
    SVN_ERR(svn_fs_paths_changed2(&changes, fs_root, pool));
            ^
/usr/local/include/subversion-1/svn_fs.h:1754:1: note: 'svn_fs_paths_changed2' has been explicitly marked deprecated here
SVN_DEPRECATED
^
/usr/local/include/subversion-1/svn_types.h:56:42: note: expanded from macro 'SVN_DEPRECATED'
#   define SVN_DEPRECATED __attribute__((deprecated))
                                         ^
svn.cpp:569:13: warning: 'svn_fs_revision_proplist' is deprecated [-Wdeprecated-declarations]
    SVN_ERR(svn_fs_revision_proplist(&revprops, fs, revnum, pool));
            ^
/usr/local/include/subversion-1/svn_fs.h:2854:1: note: 'svn_fs_revision_proplist' has been explicitly marked deprecated here
SVN_DEPRECATED
^
/usr/local/include/subversion-1/svn_types.h:56:42: note: expanded from macro 'SVN_DEPRECATED'
#   define SVN_DEPRECATED __attribute__((deprecated))
                                         ^
2 warnings generated.
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DVER="\"83d6f8d2b28e7db5c1ac959df96fc74af363ab92\"" -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I. -I/usr/include/subversion-1 -I/usr/local/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/apr-1 -I/usr/local/include/apr-1 -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I. -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib -o main.o main.cpp
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC -DVER="\"83d6f8d2b28e7db5c1ac959df96fc74af363ab92\"" -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I. -I/usr/include/subversion-1 -I/usr/local/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/apr-1 -I/usr/local/include/apr-1 -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I. -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib -o CommandLineParser.o CommandLineParser.cpp
/Library/Developer/CommandLineTools/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks -o ../svn-all-fast-export.app/Contents/MacOS/svn-all-fast-export ruleparser.o repository.o svn.o main.o CommandLineParser.o   -F/usr/local/Cellar/qt/5.11.2/lib -lsvn_fs-1 -lsvn_repos-1 -lapr-1 -lsvn_subr-1 -framework QtCore -framework DiskArbitration -framework IOKit
ld: library not found for -lsvn_fs-1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../svn-all-fast-export.app/Contents/MacOS/svn-all-fast-export] Error 1
make: *** [sub-src-make_first] Error 2

**Comment by flokli** [comment]
@grandemtn NixOS already packages this for darwin, too.

You could have a look at how it's done there: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-and-tools/svn-all-fast-export/default.nix

Hint: you can also use Nix on Darwin, next to homebrew: https://nixos.org/nix/ ;-)

**Comment by grandemtn** [comment]
Thanks so much!  I'd never heard of nix before, but using it, had this installed and working in about 5 minutes.  Thanks!

**Comment by flokli** [comment]
Glad to hear using Nix worked for you just fine :-)

**Comment by DarkGuardsman** [comment]
Any chance you can share the steps to get it working with nix?

**Comment by flokli** [comment]
@DarkGuardsman it should be only a matter of getting nix from https://nixos.org/nix/, then installing `gitAndTools.svn-all-fast-export` - please see https://nixos.org/nix/manual/#chap-quick-start.

**Comment by DarkGuardsman** [comment]
I went through that guide yesterday, never managed to get it so I could run the app through the terminal. Though I did figure out how to locate the app in the file system and extract the unix file so I could run it locally in a folder system.

**Comment by flokli** [comment]
You might need to add the profile sourcing to your .bashrc / other shells rc.

**Comment by DarkGuardsman** [comment]
I think that might have been it, I toyed with it and got it working somewhat. Problem now is it wants format 3 or 5... I think I have format 12 for the local svn repo I checked out. Does this only support specific versions?

**Comment by flokli** [comment]
Don't know anything about that - please open a new issue about that.
