### ISSUE TITLE
Svn history not migrated for folders which were copied in Svn

### ISSUE THREAD

**Issue by conradhauser** [svn-all-fast-export/svn2git#65]
I'm trying to convert a single SVN repo over to a single git repo. After migration of the svn repository to git I have noticed that git does not seem to follow svn copy operations so the resulting history is much briefer than I expect. 

To illustrate - The existing history can be viewed in tortoise svn if you uncheck the "Stop on copy/rename" checkbox while viewing a folder's history but it cannot be viewed in Git after migration.

root

- a

- b

- c

- parent project
  

  - b
  

  - c

Projects b and c were recently copied under parent-proj as part of a restructuring effort with the intention of eventually deleting them from their old locations under root. After migration the resulting git repo is missing all of the history that originated from /b and /c before the move.

I have created a SO post for this here - https://stackoverflow.com/questions/53704582/retaining-svn-copy-history-when-converting-to-git-using-kde-svn2git-tool

**Comment by jcoeltjen** [comment]
Did you have rules for projects b and c for both locations?
If you only have rules that match the path under parent project the history will be cut on the commit that was you svn copy.
There is a link in the readme to the KDE TechBase that explains the process of writing rules and how to handle svn move/copy [section 5.1](https://techbase.kde.org/Projects/MoveToGit/UsingSvn2Git).
