### ISSUE TITLE
Branch name doesn't conform to GIT standards

### ISSUE THREAD

**Issue by jkwinder** [svn-all-fast-export/svn2git#68]
I receive the following error while attempting to run a migration - "fatal: Branch name doesn't conform to GIT standards: refs/tags/AbsoluteSafe 2.0 (v301)"  
Any suggestions on what can be done about this - I'm not sure if this is a tool bug, or a limitation of the characters used in the name of the tag/branch.

**Comment by eeijlar** [comment]
Can you share the rule you are using to match this tag?

**Comment by jkwinder** [comment]
I discovered that I need to replace spaces with _ (or something else) and that has resolved my problem.

-Jeff

**Comment by jkwinder** [comment]
Here is the rule I used to do this:
match /branches/([^/]+)/
  repository <repo name>
  branch \1
  substitute branch s/ /_/
end match
