### ISSUE TITLE
std::bad_alloc on large commit

### ISSUE THREAD

**Issue by stu1811** [svn-all-fast-export/svn2git#70]
I'm trying to import a very large and ugly SVN repo on the order of 22GB. In this commit the following are deleted:
```
new/
     dir1
     dir2
     dir3
```
And the following are copied from points in the history
```
new/
     subdir/
               dir1
               dir2
               dir4
```

After running for almost 4 hours I get the following error:
terminate called after throwing an instance of 'bad_alloc'
what(): std::bad_alloc

the fast_import_crash_xxx says:
fata: EOF in data (xxxx bytes remaining)

**Comment by eeijlar** [comment]
It's likely that there are some dud commits in your SVN repository. Either someone checked in an enormous file, created a circular dependency in the commit history or created a branch with an invalid name. 

If the process gets stuck processing a node (5 minutes or more printing '+' to the screen), do ``` 
pstack <pid of svn2git>```, and locate the branch it's stuck on. Add that to the ruleset and restart the conversion.

**Comment by stu1811** [comment]
That's cool. Didn't know you about pstack. It looks like I need to expand on my rules. dir2 in the example above is actually a branches folder and needs to be expanded.

**Comment by eeijlar** [comment]
Match branches:
```
match /new/branch/([^/]+)/
  repository my-repo
  branch \1
end match
```
Skip a dud branch name (includes space):
```
match /new/branch/(branch with a)(\s)(space)/
end match
```
Make sure the last line in your file includes:

```
match /
end match
```

If your source tree has a very complex layout, you can use write a script to generate the rules for you. I exported all the branch names into a file, and then used some Perl to parse the file and generate custom rules.

**Comment by stu1811** [comment]
Adding in the recurse action where upper level directories were copied. Thanks.
