### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by k4rtik** [svn-all-fast-export/svn2git#71]
I can't get the build working, see the following
```
$ cat .qmake.stash 
QMAKE_CXX.QT_COMPILER_STDCXX = 201402L
QMAKE_CXX.QMAKE_GCC_MAJOR_VERSION = 8
QMAKE_CXX.QMAKE_GCC_MINOR_VERSION = 2
QMAKE_CXX.QMAKE_GCC_PATCH_VERSION = 1
QMAKE_CXX.COMPILER_MACROS = \
    QT_COMPILER_STDCXX \
    QMAKE_GCC_MAJOR_VERSION \
    QMAKE_GCC_MINOR_VERSION \
    QMAKE_GCC_PATCH_VERSION
QMAKE_CXX.INCDIRS = \
    /usr/include/c++/8.2.1 \
    /usr/include/c++/8.2.1/x86_64-pc-linux-gnu \
    /usr/include/c++/8.2.1/backward \
    /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include \
    /usr/local/include \
    /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed \
    /usr/include
QMAKE_CXX.LIBDIRS = \
    /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1 \
    /usr/lib \
    /lib
```
`make` fails with the following:
```
[...] # snipped
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o ../svn-all-fast-export ruleparser.o repository.o svn.o main.o CommandLineParser.o   -L -lsvn_fs-1 -lsvn_repos-1 -lapr-1 -lsvn_subr-1 -lQt5Core -lpthread   
/usr/bin/ld: svn.o: undefined reference to symbol 'svn_fs_file_contents'
/usr/bin/ld: /usr/lib/libsvn_fs-1.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:203: ../svn-all-fast-export] Error 1
make[1]: Leaving directory '/home/kartik/Projects/svn2git/src'
make: *** [Makefile:47: sub-src-make_first] Error 2
```

**Comment by Vampire** [comment]
I'm no expert in c++ builds and makefiles, but this looks spurious: `CommandLineParser.o   -L -lsvn_fs-1`
`-L` expects a directory as argument, as none is given, I guess `-lsvn_fs-1` is used as argument and then is missing on its own which would add the `svn_fs_file_contents` to the linker context which it complains is missing.
So somehow where something should come after `-L`, comes nothing.
Do you have all pre-requisites on your box?

**Comment by k4rtik** [comment]
```
diff --git a/src/src.pro b/src/src.pro
index 426d304..521b53c 100644
--- a/src/src.pro
+++ b/src/src.pro
@@ -28,7 +28,7 @@ DEPENDPATH += .
 QT = core
 
 INCLUDEPATH += . $$SVN_INCLUDE $$APR_INCLUDE
-!isEmpty($$SVN_LIBDIR): LIBS += -L$$SVN_LIBDIR
+#!isEmpty($$SVN_LIBDIR): LIBS += -L$$SVN_LIBDIR
```
After making the above change, the build works. Thanks for your help!

I do not understand why `!isEmpty()` is true above. I do not have `SVN_LIBDIR` in my environment AFAIK.

**Comment by Vampire** [comment]
This can easily be reproduced using

```bash
docker run -it --rm archlinux/base
pacman --noconfirm -Sy git gcc make qt5-base apr subversion
git clone https://github.com/svn-all-fast-export/svn2git
cd svn2git
qmake
make
```

**Comment by Vampire** [comment]
Actually the build also told you about the problem:

```
[root@170c996e434c svn2git]# make
cd src/ && ( test -e Makefile || /usr/sbin/qmake -o Makefile /svn2git/src/src.pro ) && make -f Makefile
/svn2git/src/src.pro:31: isEmpty(var) requires one argument.
make[1]: Entering directory '/svn2git/src'
```
At least on first execution (when there is no `src/Makefile` as it is during its generation where the error happens)

**Comment by Vampire** [comment]
Ok, the line should read
`!isEmpty(SVN_LIBDIR): LIBS += -L$$SVN_LIBDIR`
instead of
`!isEmpty($$SVN_LIBDIR): LIBS += -L$$SVN_LIBDIR`
On Linux and Windows I didn't have this problem before.
I don't know whether Archlinux is the culprit or maybe a different Qt version that behaves differently with the wrong syntax.

Even here, `isEmpty($$SVN_LIBDIR)` behaves wrongly, but the wrong behavior is, that it is always true, not always false like in arch linux.

**Comment by Vampire** [comment]
PR #72 fixes the problem
