### ISSUE TITLE
The command '/bin/sh -c cd /usr/local/svn2git && qmake && make' returned a non-zero code: 1

### ISSUE THREAD

**Issue by kilokili777** [svn-all-fast-export/svn2git#79]
Step 4/7 : ADD . /usr/local/svn2git
 ---> Using cache
 ---> 8b89fdb5ba3b
Step 5/7 : RUN cd /usr/local/svn2git && qmake && make
 ---> Running in 7b3a74125f6e
Usage: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *.c; *.ui; *.y; *.l; *.ts; *.xlf; *.qrc; *.h; *.hpp; *.hh; *.hxx; *.H; *.cpp; *.cc; *.cxx; *.C
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options

The command '/bin/sh -c cd /usr/local/svn2git && qmake && make' returned a non-zero code: 1

**Comment by kilokili777** [comment]
Docker version 18.09.7, build b81f47481d
Running on RH7

**Comment by nega0** [comment]
try `/bin/sh -c "cd /usr/local/svn2git && qmake && make"`. note the double-quotes.

**Comment by kilokili777** [comment]
Well then shouldn't the Dockerfile for this project be updated?

RUN cd /usr/local/svn2git && qmake && make

**Comment by hartwork** [comment]
This seems to be obsolete, worked fine with latest commit 189d926f93b2b6b5bed32dbc603d934c21e6043d .
