### ISSUE TITLE
CI? GitHub Actions? Travis?

### ISSUE THREAD

**Issue by hartwork** [svn-all-fast-export/svn2git#87]
Hi!

Are there any plans to add CI here? Would you welcome PRs with basic GitHub Actions or Travis integration?

Best, Sebastian

**Comment by tnyblom** [comment]
Hi,

I would gladly welcome any patches that enhances CI. But you are also one of the owners... ;)

**Comment by hartwork** [comment]
Hi!

I wanted to hear any existing opinions if any. I somehow overlooked 7ed33c6b110d89a69055c9272f247701f060ed3f and [its build](https://travis-ci.com/svn-all-fast-export/svn2git/builds/111927264) previously. Let me do something similar using GitHub Actions for a start: It seems fast and is integrated well. Stay tuned :smiley:

Best, Sebastian
