### ISSUE TITLE
svn-ignore switch apparently has no effect

### ISSUE THREAD

**Issue by philippn** [svn-all-fast-export/svn2git#90]
Hi there,

I'm currently working on migrating a huge SVN repo into Git using your tool. I found it to do the job quite nicely (thanks for that!), however I have stumbled across one slight issue:

I'm passing the following parameters: `--identity-map xyz.authors --rules xyz.rules --add-metadata --stats --svn-ignore --commit-interval 1000 /tmp/svn/`

However, in the resulting repo, I see no gitignore files although svn ignore properties are existing in the repo.

Am I doing something wrong or is there some way to further troubleshoot this problem?

Thanks in advance and kind regards,
Philipp

**Comment by ymartin59** [comment]
You should find a ".gitignore" in each folder corresponding to "svn:ignore" original location

**Comment by philippn** [comment]
Hi there, 
I have tested again with the latest changes and its working nicely now. Thanks a lot!

Kind regards,
Philipp
